#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha1
kind: ClusterStore
metadata:
  name: #@ "store-" + data.values.USER_ID
spec:
  sources:  
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_go@sha256:27b33492bfb9d8116b2689237161aecdaf7033a0f4b1e917481a70b58575ab2d
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_java@sha256:e7fd464a33a3c72c06874810719a03f88a3d45434c982ee9c0ae8f6434a53697
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_nodejs@sha256:bc68b0d3c42eff1b9729c6a20fd22a1669a463c8adc4bbae2757972bcd5a6476
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_java-native-image@sha256:1470f053e4cc0d912d356f2299ae3fa195ab1baaabf1ce095cde184dab6759cc
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_dotnet-core@sha256:6d57e312e7ac86f78ece4afcc3967e5314fbb71fe592800fd6f0f58bd923945a
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_python@sha256:6364d1cc1695f9a20a65604d61f6ca8ceb05567d1512f67d13b7c150f326bf08
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_php@sha256:27f003c0ad6d45fd78cd9dbb71ae55b5ba1e599d8facfd98269dd29f42028870
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_nginx@sha256:5798dfecab8a4c67bbc3b956b6bef4474c52197b8949f02b8b866e19bfcde71e
  - image: registry.lab.livefire.dev/tanzu/build-service/tanzu-buildpacks_httpd@sha256:4e15987d21d3d4f0cbc6be0d3b283db1d3f368eb15d0b1b59d835899c8bf946c
  - image: registry.lab.livefire.dev/tanzu/build-service/paketo-buildpacks_procfile@sha256:cc3910850249adb0b7b2f6850a362dbfbfad1df976b8736ac2c90ff70093fb4e
