#@ load("@ytt:data", "data")

apiVersion: kpack.io/v1alpha1
kind: ClusterStack
metadata:
  name: #@ "stack-" + data.values.USER_ID
spec:
  id: io.buildpacks.stacks.bionic
  buildImage:
    image: registry.lab.livefire.dev/tanzu/build-service/build@sha256:b133e250f0c85f031f07eb9f65bd55a27b25180591eace5c2b26e84e1f3da07e
  runImage:
    image: registry.lab.livefire.dev/tanzu/build-service/run@sha256:da5a2cef27b6ced0f535a7b0083ed2d321eb3d5b3549ab492872506dfd5a8bb8
